# Generated by Django 3.0.5 on 2025-06-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
